config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       pages#home
#            user_password POST   /users/password(.:format)               devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)           devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)          devise/passwords#edit
#                          PATCH  /users/password(.:format)               devise/passwords#update
#                          PUT    /users/password(.:format)               devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                 devise/registrations#cancel
#        user_registration POST   /users(.:format)                        devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                   devise/registrations#edit
#                          PATCH  /users(.:format)                        devise/registrations#update
#                          PUT    /users(.:format)                        devise/registrations#update
#                          DELETE /users(.:format)                        devise/registrations#destroy
#         new_user_session GET    /login(.:format)                        users/sessions#new
#             user_session POST   /login(.:format)                        users/sessions#create
#     destroy_user_session DELETE /logout(.:format)                       users/sessions#destroy
#                    about GET    /about(.:format)                        pages#about
#                  contact GET    /contact(.:format)                      pages#contact
#                      faq GET    /faq(.:format)                          pages#faq
#                     help GET    /help(.:format)                         pages#help
#                          GET    /:username(.:format)                    users#show
#                bookmarks GET    /:username/bookmarks(.:format)          bookmarks#index
#                          POST   /:username/bookmarks(.:format)          bookmarks#create
#             new_bookmark GET    /:username/bookmarks/new(.:format)      bookmarks#new
#            edit_bookmark GET    /:username/bookmarks/:id/edit(.:format) bookmarks#edit
#                 bookmark GET    /:username/bookmarks/:id(.:format)      bookmarks#show
#                          PATCH  /:username/bookmarks/:id(.:format)      bookmarks#update
#                          PUT    /:username/bookmarks/:id(.:format)      bookmarks#update
#                          DELETE /:username/bookmarks/:id(.:format)      bookmarks#destroy
#                   topics GET    /:username/topics(.:format)             topics#index
#                          POST   /:username/topics(.:format)             topics#create
#                new_topic GET    /:username/topics/new(.:format)         topics#new
#               edit_topic GET    /:username/topics/:id/edit(.:format)    topics#edit
#                    topic GET    /:username/topics/:id(.:format)         topics#show
#                          PATCH  /:username/topics/:id(.:format)         topics#update
#                          PUT    /:username/topics/:id(.:format)         topics#update
#                          DELETE /:username/topics/:id(.:format)         topics#destroy
#

Rails.application.routes.draw do
  root 'pages#home'

# Devise
  devise_for :users, skip: [:sessions], controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
  end

# Static pages
  %w[about contact faq help].each do |page|
    get page, controller: "pages", action: page
  end

  get 'bookmarks/new', to: "bookmarks#new"
# bookmarks and topics routes
  scope ":username" do
    get '', to: "users#show"
    resources :bookmarks
    resources :topics
  end
end

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id          :integer          not null, primary key
#  url         :string
#  title       :string
#  description :text
#  flag_id     :integer
#  topic_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  slug        :string
#

class Bookmark < ApplicationRecord
  extend FriendlyId
  attr_accessor :topic_name
  belongs_to :flag
  belongs_to :topic
  belongs_to :user
  belongs_to :host

  friendly_id :title, use: [:slugged, :finders]

  validates :title, presence: { message: "title cannot be blank." }
  validates :url, presence: { message: "You must enter some url." }
  validates :url, uniqueness: { scope: [:user_id, :topic_id], message: "you've already bookmarked this page, choose different topic to bookmark again." }

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
    where("url ILIKE ?", "%#{search}%")
  end

  # def topic_name
  #   topic.try(:name)
  # end
  #
  # def topic_name=(name)
  #   self.topic = Topic.where(name: name).first_or_create
  #   # self.topic = Topic.find_or_create_by(name: name)
  # end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    # TODO - consider moving seach and paging code to model
    @bookmarks = current_user.bookmarks
    if params[:search]
      @bookmarks = @bookmarks.search(params[:search]).includes(:topic, :flag).order("created_at DESC").page(params[:page]).per_page(10)
    else
      @bookmarks = @bookmarks.includes(:topic, :flag).order("created_at DESC").page(params[:page]).per_page(10)
    end
  end

  def show
  end

  def new
    @bookmark = Bookmark.new

    if params[:url]
      render 'bookmarks/form_for_extension', {bookmark: @bookmark}
    end
  ### the block of code below is left for future references.
    # request.query_parameters
    # params.each do |key,value|
    #   Rails.logger.warn "Param from chrome -> #{key}: #{value}"
    # end
  end

  def create
    # binding.pry
    @bookmark = current_user.bookmarks.build(bookmark_params)

    # ensure 'topic_name' exists otherwise it sets the 'topic_id' to nil
    if params[:topic_name].present?
      new_topic = current_user.topics.find_or_create_by(name: params[:topic_name])
      @bookmark.topic_id = new_topic.id
    end

    if @bookmark.save
      redirect_to bookmark_path(current_user, @bookmark), notice: "Bookmark saved."
    else
      render :new, notice: "Fix the errors."
    end
  end

  def edit
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to bookmark_path(current_user, @bookmark), notice: "Updated succefully."
    else
      render :edit, error: "Fix the errors"
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path(current_user), notice: "Bookmark delted."
  end

private

  def set_bookmark
    @bookmark = Bookmark.friendly.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:url, :title, :flag_id, :favicon, :hostname, :topic_id, :topic_name, :description, :slug, topics_attributes: [:id, :name])
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper

  def set_url

  end

  # TODO refactor it to use case statements instead.
  def flag_color(flag)
    if flag.name == "important" # important
      "bl_bookmarks__item--flag__important ion-record"
    elsif flag.name == "very important" # very important
      "bl_bookmarks__item--flag__very-important ion-record"
    elsif flag.name == "normal" # normal
      "bl_bookmarks__item--flag__normal ion-record"
    end
  end

end

app/views/bookmarks/_bookmark.html.erb
<div class="bl_bookmarks__item">
  <!-- Title -->
  <% if bookmark.title.present? %>
    <%= link_to bookmark_path(current_user, bookmark), class: "bl_bookmarks__item--a-tag" do %>
      <h5 class="bl_bookmarks__item--title">
        <span class="<%= flag_color(bookmark.flag) if bookmark.flag.present? %>" title="<%= bookmark.flag.name if bookmark.flag.present? %>">
        <span class="bl_favicon"><%= image_tag bookmark.favicon if bookmark.favicon? %></span>
        </span><%= bookmark.title %></h5>
    <% end %>
  <% end %>
  <!-- Url -->
    <p class="bl_bookmarks__item--url"><a href="<%= bookmark.url %>"> <%= bookmark.url %> </a></p>

  <!-- Meta section -->
    <section class="clearfix bl_bml__item--meta">
        <div class="float-left bl_bml__item--meta__topic">
          <% if bookmark.topic.present? %>
            <i class="ion-ios-list-outline bl_bml__item--meta__topic--icon" title="Topic name"></i>
            <span class=" hvr-grow bl_bml__item--meta__topic--name"><%= link_to bookmark.topic.name, topic_path(current_user, bookmark.topic) %></span>
            <% if bookmark.topic.is_public? %> <i class="ion-ios-people bl_bml__item--meta__lock--icon" title="This topic is public"></i> <% end %>
          <% end %>
        </div>

        <div class="float-right">
            <date><%= bookmark.created_at.strftime("%d %b %Y") %></date>
        </div>
    </section>
</div>

app/views/bookmarks/_form.html.erb
<div class="bl_bookmark__form">
    <% if @bookmark.errors.any? %>
      <p class="bl_error">Fix the errors and try again</p>
    <% end %>

    <%= form_for(bookmark, url: url) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "title" %>
      <p class="help-text bl_error"><%= @bookmark.errors[:title].first %></p>

      <%= f.label :url %>
      <%= f.text_field :url, placeholder: "url"  %>
      <p class="help-text bl_error"><%= @bookmark.errors[:url].first %></p>

      <%= f.label :description %>
      <%= f.text_field :description, placeholder: "description"  %>

      <%= f.label :flag %>
      <%= f.collection_radio_buttons :flag_id, Flag.all, :id, :name%>

      <%= f.label :topic %>
      <%= f.collection_select :topic_id, Topic.where(user_id: current_user), :id, :name , {include_blank: true}, {id: "topic-select"} %>

      <%#= f.collection_select :topic_name, Topic.where(user_id: current_user), :name, :name, {include_blank: true}, {id: "topic-select"} %>

      <br>
      <%= f.submit "save", { class: "button secondary"} %>
    <% end %>
</div>

app/views/bookmarks/_paginate.html.erb
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @bookmarks %>
  </div>
  <%= will_paginate @bookmarks, :container => false %>
</div>

app/views/bookmarks/edit.html.erb
<div class="row columns bl_bookmark__edit">
  <h3>Bookmark edit</h3>

  <%= render "form", bookmark: @bookmark, url: bookmark_path(current_user, @bookmark) %>
</div>

app/views/bookmarks/form_for_extension.html.erb
<div class="row columns  bl_bookmark__new--extension">
    <section class="bl_bookmark__new--extension__chrome--icon">
      <% if params[:favicon]%>
        <span class="bl_favicon"><%= image_tag params[:favicon] %></span>
      <% else %>
        <span class="ion-social-chrome-outline" title="thank you for using chrom extension :)"></span>
      <% end %>
    </section>
    <div class="bl_bookmark__new--extension__form">
      <%= form_for(@bookmark, url: bookmarks_path(current_user)) do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title, value: params[:title], placeholder: "title" %>

        <%= f.label :url %>
        <%= f.text_field :url, value: params[:url], placeholder: "url" %>

        <%= f.label :description %>
        <%= f.text_field :description, placeholder: "description" %>

        <%= f.label :flag %>
        <%= f.collection_radio_buttons :flag_id, Flag.all, :id, :name%>

        <%= f.label :topic, class: "topic_label" %>
        <p class="help-text">choose existing or <span class="bl_bookmark__new--extension__form--new_topic--toggle">create new topic</span></p>
        <%= f.collection_select :topic_id, Topic.where(user_id: current_user), :id, :name, {include_blank: true}, {id: "topic-select"} %>


        <%= text_field_tag :topic_name, nil, placeholder: "new topic name", class: "bl_bookmark__new--extension__form--new_topic--input" %>

        <%#= f.collection_select :topic_name, Topic.where(user_id: current_user), :name, :name, {include_blank: true}, {id: "topic-select"} %>

        <%= f.hidden_field :favicon, value: params[:favicon] %>
        <%= f.hidden_field :hostname, value: params[:hostname] %>
        <br>
        <%= f.submit "save", { class: "button secondary"} %>
      <% end %>
    </div>
</div>

app/views/bookmarks/index.html.erb
<%= page_title "Bloi - Bookmarks" %>

<div class="row columns bl_tools__wrapper clearfix">
    <section class="float-left">
        <div class="bl_tools__count--wrapper">
            <%= @bookmarks.count %>
        </div>
    </section>
    <section class="float-right">
      <%= form_tag(bookmarks_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "search", class: "bl_tools__search" %>
      <% end %>
    </section>
</div>


<div class="row columns  bl_bookmarks__list">
  <% if @bookmarks.empty? && !params[:search].present? %>
    <div class="bl_bookmarks__empty">
      <h4 class="bl_bm_empty__lead">You don't seem to have any bookmarks.</h4>
      <%= link_to "https://chrome.google.com/webstore/detail/bloi-remote/embnkiohgnkdphjimblpbijihphlllcd" do %><div class="bl_bm_empty__store"><%= image_tag "webstore.png" %></div><% end %>
      <p class="bl_bm_empty__link">Download <a href="https://chrome.google.com/webstore/detail/bloi-remote/embnkiohgnkdphjimblpbijihphlllcd">Bloi - chrome extention</a> to quickly save new bookmarks.</p>
      <p class="bl_bm_empty__link">or</p>
      <p class="bl_bm_empty__link"><%= link_to "Create new", new_bookmark_path(current_user) %></p>
    </div>
  <% end %>
  <%= render @bookmarks %>
</div>

<%#= will_paginate @bookmarks, :page_links => true %>
<%= render "paginate", object: @bookmarks %>

app/views/bookmarks/index.js.erb
$('.bl_bookmarks__list').append('<%= j render(@bookmarks) %>');
<% if @bookmarks.next_page %>
  // $('.digg_pagination').replaceWith('<%= j will_paginate(@bookmarks) %>');
  $('.digg_pagination').replaceWith('<%= j render "paginate", object: @bookmarks %>');
<% else %>
  $('.digg_pagination').remove();
<% end %>

app/views/bookmarks/new.html.erb
<div class="row columns  bl_bookmark__new">
  <h3>New bookmark</h3>
  <%= render "form", bookmark: @bookmark, url: bookmarks_path(current_user) %>
</div>

app/views/bookmarks/show.html.erb
<%= page_title "Bloi - #{@bookmark.title}" %>

<div class="row columns  bl_bookmarks__show">

  <!-- Title -->
  <% if @bookmark.title.present? %>
      <h5 class="bl_bookmarks__show--title"><%= @bookmark.title %></h5>
  <% end %>

  <!-- Url -->
    <p class="bl_bookmarks__show--url"><a href="<%= @bookmark.url %>"> <%= @bookmark.url %> </a></p>

  <!-- Description -->
    <% if @bookmark.description.present? %>
      <p class="bl_bookmarks__show--description"> <%= @bookmark.description %> </p>
    <% end %>

  <!-- Meta section -->
    <section class="clearfix bl_bookmarks__show--meta">
        <div class="float-left bl_bookmarks__show--meta__topic">
          <% if @bookmark.topic.present? %>
            <i class="ion-ios-list-outline bl_bookmarks__show--meta__topic--icon"></i>
            <span class="bl_bookmarks__show--meta__topic--name"><%= link_to @bookmark.topic.name, topic_path(current_user, @bookmark.topic) %></span>
            <% if @bookmark.topic.is_public? %> <i class="ion-ios-people bl_bml__item--meta__lock--icon" title="This topic is public"></i> <% end %>
          <% end %>
        </div>

        <div class="float-right">
            <date><%= @bookmark.created_at.strftime("%d %b %Y") %></date>
        </div>
    </section>
</div>

<div class="bl_bookmarks__show--actions">
  <ul class="menu simple">
    <li><%= link_to "Edit", edit_bookmark_path(current_user, @bookmark) %></li>
    <li><%= link_to 'Delete', bookmark_path(current_user, @bookmark), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</div>