config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       pages#home
#            user_password POST   /users/password(.:format)               devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)           devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)          devise/passwords#edit
#                          PATCH  /users/password(.:format)               devise/passwords#update
#                          PUT    /users/password(.:format)               devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                 devise/registrations#cancel
#        user_registration POST   /users(.:format)                        devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                   devise/registrations#edit
#                          PATCH  /users(.:format)                        devise/registrations#update
#                          PUT    /users(.:format)                        devise/registrations#update
#                          DELETE /users(.:format)                        devise/registrations#destroy
#         new_user_session GET    /login(.:format)                        users/sessions#new
#             user_session POST   /login(.:format)                        users/sessions#create
#     destroy_user_session DELETE /logout(.:format)                       users/sessions#destroy
#                    about GET    /about(.:format)                        pages#about
#                  contact GET    /contact(.:format)                      pages#contact
#                      faq GET    /faq(.:format)                          pages#faq
#                     help GET    /help(.:format)                         pages#help
#                          GET    /:username(.:format)                    users#show
#                bookmarks GET    /:username/bookmarks(.:format)          bookmarks#index
#                          POST   /:username/bookmarks(.:format)          bookmarks#create
#             new_bookmark GET    /:username/bookmarks/new(.:format)      bookmarks#new
#            edit_bookmark GET    /:username/bookmarks/:id/edit(.:format) bookmarks#edit
#                 bookmark GET    /:username/bookmarks/:id(.:format)      bookmarks#show
#                          PATCH  /:username/bookmarks/:id(.:format)      bookmarks#update
#                          PUT    /:username/bookmarks/:id(.:format)      bookmarks#update
#                          DELETE /:username/bookmarks/:id(.:format)      bookmarks#destroy
#                   topics GET    /:username/topics(.:format)             topics#index
#                          POST   /:username/topics(.:format)             topics#create
#                new_topic GET    /:username/topics/new(.:format)         topics#new
#               edit_topic GET    /:username/topics/:id/edit(.:format)    topics#edit
#                    topic GET    /:username/topics/:id(.:format)         topics#show
#                          PATCH  /:username/topics/:id(.:format)         topics#update
#                          PUT    /:username/topics/:id(.:format)         topics#update
#                          DELETE /:username/topics/:id(.:format)         topics#destroy
#

Rails.application.routes.draw do
  root 'pages#home'

# Devise
  devise_for :users, skip: [:sessions], controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
  end

# Static pages
  %w[about contact faq help].each do |page|
    get page, controller: "pages", action: page
  end

  get 'bookmarks/new', to: "bookmarks#new"
# bookmarks and topics routes
  scope ":username" do
    get '', to: "users#show"
    resources :bookmarks
    resources :topics
  end
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  is_public   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  slug        :string
#

class Topic < ApplicationRecord
  extend FriendlyId
  has_many :bookmarks, dependent: :destroy
  belongs_to :user

  friendly_id :name, use: [:slugged, :finders]

  scope :of, ->(user) {where(user_id: user.id) if user.present?}

  validates :name, presence: { message: "topic name cannot be blank." }
  validates :name, uniqueness: { scope: [:user_id], message: "You already seem to have a topic with this name." }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    # TODO - search for bookmars.title & url
    # TODO - consider pagination for topics
    # TODO - limit urls to 5 for each topic
    # TODO - create scopes
    @topics = current_user.topics.includes(:bookmarks)
    if params[:search]
      @topics = @topics.where("name ilike ?", "%#{params[:search]}%")
    else
      @topics
    end
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topic_path(current_user, @topic), notice: "Topic saved."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path(current_user, @topic), notice: "Updated succefully."
    else
      render :edit
    end
  end

  def destroy
    if @topic.destroy
      redirect_to topics_path(current_user), notice: "Deleted succefully."
    else
      redirect_to topics_path(current_user), notice: "Failed to delete."
    end
  end

private

  def set_topic
    @topic = Topic.friendly.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name, :description, :is_public, :slug)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="bl_topic__form">

    <% if @topic.errors.any? %>
      <p class="bl_error">Fix the errors and try again</p>
    <% end %>

    <%= form_for(topic, url: url) do |f| %>

      <%= f.label "Topic name" %>
      <%= f.text_field :name, placeholder: "name" %>
      <p class="help-text bl_error"><%= @topic.errors[:name].first %></p>

      <%= f.label "Topic description" %>
      <%= f.text_field :description, placeholder: "description" %>

      <%= f.check_box :is_public, id: "topic_is_pulbic" %><label for="topic_is_pulbic">Make it public?</label>
      <br>
      <%= f.submit "Create", class: "button secondary" %>
    <% end %>
</div>

app/views/topics/edit.html.erb
<%= page_title "Bloi - topic edit" %>

<div class="row columns  bl_topic__edit">
  <h3>Topics edit</h3>

  <%= render "form", topic: @topic, url: topic_path(current_user, @topic) %>

</div>

app/views/topics/index.html.erb
<%= page_title "Topics" %>

<div class="row columns  bl_tools__wrapper clearfix">
    <section class="float-left">
        <div class="bl_tools__count--wrapper">
            <span><%= @topics.count %></span>
        </div>
        <div class="bl_tools__new--wrapper">
          <%= link_to "Create new topic", new_topic_path(current_user) %>
            <!-- <a href="">Create new topic</a> -->
        </div>
    </section>
    <section class="float-right">
      <%= form_tag(topics_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "search", class: "bl_tools__search" %>
      <% end %>
    </section>
</div>

<div class="row columns  bl_topics__list">
  <% if @topics.empty?  && !params[:search].present?  %>
    <div class="bl_topics__empty">
      <h4 class="bl_tp_empty__lead">You don't seem to have any topics.</h4>
      <p class="bl_tp_empty__link"><%= link_to "Create new", new_topic_path(current_user) %></p>
    </div>
  <% end %>
   <% @topics.each do |topic| %>
    <div class="bl_topics__item">
        <section class="bl_tp__title--wrapper clearfix">
          <%= link_to topic_path(current_user, topic), class: "bl_tp__title--a-tag" do %>
            <h5 class="bl_tp__title float-left"> <%= topic.name %> </h5>
            <% if topic.is_public? %> <i class="ion-ios-people bl_tp__title--public-icon" title="This topic is public"></i> <% end %>
          <% end %>
            <div class="bl_tp__count float-right"> <%= topic.bookmarks.count %> </div>
        </section>

        <section class="bl_tp__links--wrapper">
            <ul class="bl_tp__links--list">
              <% topic.bookmarks.each do |bm| %>
                <li class="bl_tp__links--item"><%= link_to bm.title, bookmark_path(current_user, bm) %></li>
              <% end %>
            </ul>
        </section>
    </div>
    <% end %>
</div>

app/views/topics/new.html.erb
<%= page_title "Bloi - topic new" %>


<div class="row columns  bl_topic__new">
  <h3>New topic</h3>

  <%= render "form", topic: @topic, url: topics_path %>

</div>

app/views/topics/show.html.erb
<%= page_title "Bloi - #{@topic.name}" %>

<div class="row columns  bl_topics__show">

  <!-- Name -->

  <section class="bl_topics__show__name--wrapper clearfix">
      <h5 class="bl_topics__show--name float-left"> <%= @topic.name %> </h5>
      <% if @topic.is_public? %> <i class="ion-ios-people bl_topics__show--name--public-icon" title="This topic is public"></i> <% end %>
      <div class="bl_topics__show--count float-right"> <%= @topic.bookmarks.count %> </div>
  </section>

  <!-- Description -->
    <% if @topic.description.present? %>
      <p class="bl_topics__show--description"> <%= @topic.description %> </p>
    <% end %>

  <!-- Links -->
  <section class="bl_topics__show__links--wrapper">
      <ul class="bl_topics__show__links--list">
        <% @topic.bookmarks.each do |bm| %>
          <li class="bl_topics__show__links--item"><%= link_to bm.title, bookmark_path(current_user, bm) %></li>
        <% end %>
      </ul>
  </section>
</div>



<div class="bl_topics__show--actions">
  <ul class="menu simple">
    <li><%= link_to "Edit", edit_topic_path(current_user, @topic) %></li>
    <li><%= link_to 'Delete', topic_path(current_user, @topic), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</div>