config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       pages#home
#            user_password POST   /users/password(.:format)               devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)           devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)          devise/passwords#edit
#                          PATCH  /users/password(.:format)               devise/passwords#update
#                          PUT    /users/password(.:format)               devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                 devise/registrations#cancel
#        user_registration POST   /users(.:format)                        devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                   devise/registrations#edit
#                          PATCH  /users(.:format)                        devise/registrations#update
#                          PUT    /users(.:format)                        devise/registrations#update
#                          DELETE /users(.:format)                        devise/registrations#destroy
#         new_user_session GET    /login(.:format)                        users/sessions#new
#             user_session POST   /login(.:format)                        users/sessions#create
#     destroy_user_session DELETE /logout(.:format)                       users/sessions#destroy
#                    about GET    /about(.:format)                        pages#about
#                  contact GET    /contact(.:format)                      pages#contact
#                      faq GET    /faq(.:format)                          pages#faq
#                     help GET    /help(.:format)                         pages#help
#                          GET    /:username(.:format)                    users#show
#                bookmarks GET    /:username/bookmarks(.:format)          bookmarks#index
#                          POST   /:username/bookmarks(.:format)          bookmarks#create
#             new_bookmark GET    /:username/bookmarks/new(.:format)      bookmarks#new
#            edit_bookmark GET    /:username/bookmarks/:id/edit(.:format) bookmarks#edit
#                 bookmark GET    /:username/bookmarks/:id(.:format)      bookmarks#show
#                          PATCH  /:username/bookmarks/:id(.:format)      bookmarks#update
#                          PUT    /:username/bookmarks/:id(.:format)      bookmarks#update
#                          DELETE /:username/bookmarks/:id(.:format)      bookmarks#destroy
#                   topics GET    /:username/topics(.:format)             topics#index
#                          POST   /:username/topics(.:format)             topics#create
#                new_topic GET    /:username/topics/new(.:format)         topics#new
#               edit_topic GET    /:username/topics/:id/edit(.:format)    topics#edit
#                    topic GET    /:username/topics/:id(.:format)         topics#show
#                          PATCH  /:username/topics/:id(.:format)         topics#update
#                          PUT    /:username/topics/:id(.:format)         topics#update
#                          DELETE /:username/topics/:id(.:format)         topics#destroy
#

Rails.application.routes.draw do
  root 'pages#home'

# Devise
  devise_for :users, skip: [:sessions], controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
  end

# Static pages
  %w[about contact faq help].each do |page|
    get page, controller: "pages", action: page
  end

  get 'bookmarks/new', to: "bookmarks#new"
# bookmarks and topics routes
  scope ":username" do
    get '', to: "users#show"
    resources :bookmarks
    resources :topics
  end
end

app/views/layouts/_footer.html.erb
<footer class="row bl_footer">
  <ul class="menu simple bl_footer__menu">
    <li><a href="https://chrome.google.com/webstore/detail/bloi-remote/embnkiohgnkdphjimblpbijihphlllcd">Browser Addon</a></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Help', help_path %></li>
    <li><%= link_to 'FAQ', faq_path %></li>
    <li><a href="/privacy.html">privacy policy</a></li>
    <li><a href="/tc.html">t&amp;c</a></li>
  </ul>
  <section class="bl_footer__copyright">
    <p>Crafted with love using awesome open-source gifts. - <span class="arrc"><a href="http://arrc.in">arrC</a></span></p>
  </section>
  <section class="bl_footer__credits">
    <ul class="menu simple">
      <li><a href="">Ruby</a></li>
      <li><a href="">Rails</a></li>
      <li><a href="">jQuery</a></li>
      <li><a href="">Sass</a></li>
      <li><a href="">Atom</a></li>
      <li><a href="">Ionicons</a></li>
      <li><a href="">Quicksand</a></li>
      <li><a href="">WorkSans</a></li>
    </ul>
  </section>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83747060-1', 'auto');
</script>

app/views/layouts/_google_analytics_pageview.html.erb
<script>
    ga('send', 'pageview', '<%= request.path %>');
</script>

app/views/layouts/_header.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title><%= content_for?(:title) ? yield(:title) : "Bloi: minimalist bookmarking app." %></title>

<%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css" media="screen" title="no title" charset="utf-8">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.0.2/css/hover-min.css" media="screen" title="no title" charset="utf-8">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= csrf_meta_tags %>
<%= render "layouts/google_analytics" %>

app/views/layouts/_navbar.html.erb
<header class="bl_primary_header">
    <div class="row">
        <section class="bl_primary_header__wrapper clearfix">
            <div class="bl_primary_header__wrapper--logo float-left">
                <% if user_signed_in? %>
                  <%= link_to 'Bloi', bookmarks_path(current_user) %>
                <% else %>
                  <%= link_to 'Bloi', root_path %>
                <% end %>
            </div>

            <div class="bl_primary_header__wrapper--user float-right">
              <% if user_signed_in? %>
                <%= link_to edit_user_registration_path do %> <i class="ion-person"></i> <% end %>
              <% end %>
            </div>
        </section>
    </div>
</header>
<header class="bl_secondary_header">
    <div class="row ">
         <section class="bl_secondary_header__wrapper">
            <div class="top-bar bl_top-bar__menu">
                <div class="top-bar-left bl_top-bar__menu--left">
                    <ul class="menu">
                      <% if user_signed_in? %>
                        <li class="<%= current_class?(bookmarks_path(current_user)) %>"><%= link_to "Bookmarks", bookmarks_path(current_user) %></li>
                        <li class="<%= current_class?(topics_path(current_user)) %>"><%= link_to "Topics", topics_path(current_user) %></li>
                      <% else %>
                        <li class="bl_tb_intro"><a>A <em>bare minimal</em>, <em>no fuss</em> &amp; <em>simple</em> bookmarking application.</a></li>
                      <% end %>
                    </ul>
                </div>
                <div class="top-bar-right bl_top-bar__menu--right">
                    <ul class="menu">
                      <% if user_signed_in? %>
                        <li class="bl_tb--right__new_bookmark <%= current_class?(new_bookmark_path(current_user)) %>">
                          <%= link_to new_bookmark_path(current_user) do %>
                            <i class="ion-plus-round"></i>
                          <% end %>
                        </li>
                      <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                        <li><%= link_to 'Login', new_user_session_path %></li>
                      <% end %>
                    </ul>
                </div>
            </div>
        </section>
    </div>
</header>

app/views/layouts/_notifications.html.erb
<% if alert  %>
  <div class="bl_flash_messages">
    <p class="bl_flash_messages--alert"><%= alert %></p>
  </div>
<% elsif notice  %>
  <div class="bl_flash_messages">
    <p class="bl_flash_messages--notice"><%= notice %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/header" %>
  </head>

  <body id="<%= params[:controller].parameterize %>_controller">
    <%= render "layouts/notifications" %>
    <div class="bl_header">
      <%= render "layouts/navbar" %>
    </div>


    <div class="row bl_content__wrapper">



      <!-- <section class="large-12 large-centered columns">
        <%#= yield %>
      </section> -->

      <%= yield %>

    </div>

    <div class="footer">
      <%= render "layouts/footer" %>
    </div>
    <script type="text/javascript">
      $(function(){ $(document).foundation(); });
      // window.sr = ScrollReveal();

      sr.reveal('.bl_bookmarks__item, .bl_topics__item', {
        origin: 'bottom',
        delay: 100,
        easing : 'cubic-bezier(0.6, 0.2, 0.1, 1)',
        duration: 400, scale: 0.9 ,
        // container: '.bl_bookmarks__list',
        reset: true,
        useDelay: 'always',
      });



      // select2
      // $(document).ready(function() {
      //   $("#topic-select").select2({
      //     tags: false
      //   });
      // });
    </script>
    <%= render "layouts/google_analytics_pageview" %>
  </body>
</html>

app/views/layouts/fdsa.html.erb
<div class="top-bar">
  <section class="row">
    <section class="large-12 large-centered columns">
      <div class="top-bar-title">
        <!-- <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
          <button class="menu-icon dark" type="button" data-toggle></button>
        </span> -->
        <strong>Bloi</strong>
      </div>
      <div id="responsive-menu">
        <div class="top-bar-left">
          <ul class="menu">
            <li><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Bookmarks", bookmarks_path(current_user) %></li>
              <li><%= link_to "Topics", topics_path(current_user) %></li>
              <li><%= link_to "New", new_bookmark_path(current_user) %></li>
            <% end %>
          </ul>
        </div>

        <div class="top-bar-right">
          <ul class="dropdown menu" data-dropdown-menu>
            <% if user_signed_in? %>
              <li><strong><%= current_user.username %></strong></li>
              <li class="has-submenu is-dropdown-submenu-parent">
                <%= link_to 'Dashboard' %>
                <ul class="submenu menu vertical" data-submenu>
                  <li><%= link_to "Aircraft editor"%></li>
                  <li><%= link_to "List"%></li>
                </ul>
              </li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </section>
  </section>
</div>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/header" %>
  </head>

  <body id="<%= params[:controller].parameterize %>_controller">
    <%= render "layouts/notifications" %>
    <div class="bl_header">
      <%= render "layouts/navbar" %>
    </div>


    <div class="bl_home_wrapper">

      <%= yield %>

    </div>

    <script type="text/javascript">
      $(function(){ $(document).foundation(); });
      // window.sr = ScrollReveal();

      sr.reveal('.bl_section_wrapper', {
        origin: 'bottom',
        delay: 100,
        easing : 'cubic-bezier(0.6, 0.2, 0.1, 1)',
        duration: 400, scale: 0.9 ,
        reset: true,
        useDelay: 'always',
      });

    </script>
  </body>
</html>